### ISSUE TITLE
Publish task list for Chairs onboarding and transition

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#243]
Based on #242 there has been some loss of information when new w3c-ccg Chairs are onboarded, and old chairs leave.

This is a tasklist for writing , followed by another tasklist of what it might look include:

Create a chair transition document
* [ ] Where, in /Community or in an issue that is copied and checked off after each transition?
* [ ] Docs needed for W3C.org page details, I've forgotten.
* [ ] What is the policy for GitHub changes? I (@ChristopherA) fortunately still have all of my admin privs for the whole community, but should I? Maybe I should be moved community-wide to a lower level, and only give me admin or maintainer for specific repos.

Chair Transitions Task List (draft):
* [ ] Transition W3C details
  * [ ] Am existing chair logs in to W3C site, goes to membership section, and changes the membership status of new chairs to be a chairperson.
  * [ ] Once that change has been confirmed (and the new chairperson can login), then any departing chairs should be removed from list.
  * [ ] Cleanup any W3C org details
* [ ] Github permissions need to be changed
  * [ ] Who changes them? How?
  * [ ] The static GitHub home page should list current chairs, update it.
* [ ] Other permissions may be required (Jitsi?)
* [ ] Schedule calls with old chairs to catch up on history.

**Comment by ChristopherA** [comment]
@kimdhamilton has a wealth of knowledge about how the /meeting repo's tools worked. Though some has changed, she may have some more ideas for 👆🏼.

**Comment by wip-abramson** [comment]
This feels like something we need to follow up on @man4prez

**Comment by wip-abramson** [comment]
cc @mkhraisha and @denkeni. Lets discuss this next chair call. I think we have some of this documented in our drive, but we may want to put it onto the repo.

I believe we still need to discuss Github permissions
