### ISSUE TITLE
Add CodeOwners for CG repos

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/community#29]
See https://help.github.com/articles/about-codeowners/

**Comment by ChristopherA** [comment]
An also list codeowners in master work items repo https://github.com/w3c-ccg/community/blob/master/work_items.md

**Comment by ChristopherA** [comment]
Add to process of creating new repos, that a codeowners file needs to be added.

**Comment by kimdhamilton** [comment]
## Progress
I added CODEOWNERS for some repos, but had some difficulties. We have a lot of items that:
- Do not currently have github repos; are being iterated on externally, and
- I am not sure whether they will remain CCG work items (or will be put on hold), per earlier conversations.

## Next steps
Here is what I think the proper resolutions are, but I'd like confirmation.

### Work items; create repos
Create repos for the following; we will continue iterating and create a spectext version in the repo eventually (and we definitely want these are work items)
- [ ] DID Explainer
- [ ] Document W3C-CCG Process
- [ ] Registries Process 

### Unsure about status of these; whether they are work items
- [ ] DID Engagement spreadsheet
- [ ] Engagement Model
- [ ] Credential Handler API and Polyfill 
- [ ] Digital Verification Specifications 

### Additional TODOs
- [ ] Add to process of creating new CCG repos, that a codeowners file needs to be added.

**Comment by kimdhamilton** [comment]
Finished checked items and added a process doc (https://w3c-ccg.github.io/create_repo.html)

I'll close this and create a new issue tracking what to do with:
- DID Engagement spreadsheet
- Engagement Model
- Credential Handler API and Polyfill
- Digital Verification Specifications
